In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
def sample_mlp(rs, in_dim, out_dim, hidden_dims, nonlinearity):
    """Sample an MLP with given dimensions and nonlinearity.

    Args:
        rs: Random state for reproducibility.
        in_dim: Input dimension.
        out_dim: Output dimension.
        hidden_dims: List of hidden layer dimensions.
        nonlinearity: Nonlinearity function to use between layers.

    Returns:
        A function representing the MLP.
    """
    layers = []
    layer_dims = [in_dim] + hidden_dims + [out_dim]
    
    for i in range(len(layer_dims) - 1):
        W = rs.normal(size=(layer_dims[i], layer_dims[i+1])) * np.sqrt(2. / layer_dims[i])
        b = rs.normal(size=(layer_dims[i+1],)) * 0.01
        layers.append((W, b))
    
    def mlp(x):
        for i, (W, b) in enumerate(layers):
            x = x @ W + b
            if i < len(layers) - 1:
                x = nonlinearity(x)
        return x
    
    return mlp

In [3]:
def sample_matrix_product(rs, dim, n, distribution='normal'):
    """Sample a product of n random matrices of size (dim, dim).

    Args:
        rs: Random state for reproducibility.
        dim: Dimension of the square matrices.
        n: Number of matrices to multiply.
        distribution: Distribution to sample from ('normal' or 'uniform').

    Returns:
        The resulting matrix product.
    """
    if distribution == 'normal':
        matrices = [rs.normal(size=(dim, dim)) for _ in range(n)]
    elif distribution == 'uniform':
        matrices = [rs.uniform(size=(dim, dim)) for _ in range(n)]
    else:
        raise ValueError("Unsupported distribution type.")

    M_prod = np.eye(dim)
    for M in matrices:
        M_prod = M_prod @ M
    return M_prod

In [4]:
rs = np.random.RandomState(42)

In [ ]:
# Single randomly sampled matrix:
M_0 = rs.uniform(size=(4, 4)) + np.eye(4)

# Get singular values and vectors
U, S, VT = np.linalg.svd(M_0)

print(f"Singular values of M_0: {S}")

Singular values of M_0: [1.56779665 0.61255569 0.40652755 0.16321735]


In [5]:
dim = 4

M_prod = sample_matrix_product(rs, dim=dim, n=4, distribution='uniform')

# Get singular values and vectors
U_prod, S_prod, VT_prod = np.linalg.svd(M_prod)

print(f"Singular values of M_prod: \n{S_prod}")

print(f"Log of singular values of M_0: \n{np.log(S_prod)}")

print(f"M_prod: \n{M_prod}")

# Sample random points in R^dim, plot resulting transformation in R^2
samples = rs.normal(size=(1000, dim))

final_proj_matrix = np.asarray([[1, 0, 0, 0],
                                [0, 1, 0, 0]])

transformed_samples = samples @ M_prod.T @ final_proj_matrix.T

Singular values of M_prod: 
[1.24798459e+01 6.87255274e-02 4.50223519e-02 5.26331430e-04]
Log of singular values of M_0: 
[ 2.52411501 -2.67763457 -3.1005962  -7.54957945]
M_prod: 
[[4.06619936 3.59918567 4.6910824  4.641867  ]
 [1.85491016 1.64606118 2.12646616 2.06120898]
 [3.37327192 2.9893923  3.87554787 3.77919688]
 [2.01315194 1.75969212 2.38732252 2.30762211]]


In [6]:
transformed_samples.shape

(1000, 2)

In [69]:
M_prod

array([[2.88636578, 3.91571607, 2.40454475, 3.46618001],
       [1.33285169, 1.78920109, 1.0949539 , 1.57547443],
       [1.57695877, 2.09262345, 1.24829503, 1.80520526],
       [1.30725179, 1.76649148, 1.06911922, 1.5460299 ]])

In [62]:
# Take element wise nth root of singular values of M_prod
M_prod_root = np.power(M_prod, 1/4)

In [63]:
M_prod_root

array([[1.42002885, 1.37737141, 1.47169653, 1.46782126],
       [1.16702651, 1.13269111, 1.20757641, 1.19820329],
       [1.35522947, 1.31490909, 1.40308272, 1.39427962],
       [1.19115736, 1.15175252, 1.24301902, 1.23251205]])

In [107]:
# Sample many matrices, compute their mean
n_samples = 1000
dim = 4
# M_samples = [sample_matrix_product(rs, dim=dim, n=4, distribution='uniform') for _ in range(n_samples)]
M_samples = [(rs.uniform(size=(4, 4)) @ rs.uniform(size=(4, 4))) for _ in range(n_samples)]
M_mean = np.mean(M_samples, axis=0)
M_var = np.var(M_samples, axis=0)

In [108]:
M_mean

array([[1.00506212, 0.9858713 , 0.9888983 , 1.00961495],
       [0.99303838, 0.97873214, 0.98095541, 0.98921197],
       [1.00401489, 0.99616976, 0.99599523, 1.00426463],
       [1.00836521, 0.98900559, 0.99371745, 1.00976683]])

In [109]:
M_var

array([[0.1997542 , 0.18108135, 0.18096347, 0.20847721],
       [0.19782974, 0.18599035, 0.18048298, 0.18808268],
       [0.19142767, 0.18397398, 0.1924513 , 0.20038092],
       [0.18791318, 0.1792648 , 0.18447891, 0.19639423]])

In [97]:
(4**3) * ((1/3)**4 - (1/2)**8)

0.5401234567901233

In [111]:
4*(7/(16*9))


0.19444444444444445